Fatal error: exception Failure("return outside function")